import { ProjectPlotFormData } from "@/components/project/projectConfigOpenDialog";

export const DEMO_PRESETS: ProjectPlotFormData[] = [
  {
    userId: "",
    title: "Verdant Horizon Villa",
    description:
      "A spacious 2700 sq. ft. two-story residential villa situated on a premium north-facing corner plot. The design carefully accommodates a 5ft eastern setback and preserves a mature oak tree near the rear boundary.",
    buildingType: "residential",
    totalFloors: 2,
    activeFloorNumber: 1,
    status: "draft",
    isPublic: true,
    shapeType: "rectangular",
    width: 45,
    height: 60,
    totalArea: 2700,
    customPoints: [],
    northFacing: true,
    cornerPlot: true,
    slopedPlot: false,
    obstacles: "Mature oak tree near rear boundary; require 5ft eastern setback.",
    plotImageUrl: "",
  },
  {
    userId: "",
    title: "Skyline Urban Duplex",
    description:
      "An approved three-story residential duplex designed for a compact 1750 sq. ft. urban lot. The architecture creatively adapts to a gentle 4-degree slope descending towards the front access road.",
    buildingType: "residential",
    totalFloors: 3,
    activeFloorNumber: 1,
    status: "approved",
    isPublic: false,
    shapeType: "rectangular",
    width: 35,
    height: 50,
    totalArea: 1750,
    customPoints: [],
    northFacing: false,
    cornerPlot: false,
    slopedPlot: true,
    obstacles: "Gentle 4-degree grade slope towards front road.",
    plotImageUrl: "",
  },
  {
    userId: "",
    title: "Apex Innovation Studio",
    description:
      "A sprawling single-story residential studio covering 4000 sq. ft. on a prime north-facing corner lot. The expansive layout strategically works around a municipal water main easement along the western boundary.",
    buildingType: "residential",
    totalFloors: 1,
    activeFloorNumber: 1,
    status: "draft",
    isPublic: true,
    shapeType: "rectangular",
    width: 50,
    height: 80,
    totalArea: 4000,
    customPoints: [],
    northFacing: true,
    cornerPlot: true,
    slopedPlot: false,
    obstacles: "Municipal water main easement along western fence.",
    plotImageUrl: "",
  },
];

export const DEMO_RESET_FOR_PROJECT: ProjectPlotFormData[] = [
  {
    userId: "",
    title: "",
    description: "",
    buildingType: "residential",
    totalFloors: 0,
    activeFloorNumber: 0,
    status: "draft",
    isPublic: true,
    shapeType: "rectangular",
    width: 0,
    height: 0,
    totalArea: 0,
    customPoints: [],
    northFacing: true,
    cornerPlot: true,
    slopedPlot: false,
    obstacles: "",
    plotImageUrl: "",
  },
];
